### ISSUE TITLE
Bevy 0.9 support

### ISSUE THREAD

**Issue by BrandonDyer64** [naia-lib/naia#103]
Love this project!

Are there plans in the works for upgrading naia to Bevy 0.9 yet?

**Comment by connorcarpenter** [comment]
Yes there is, I was kind of waiting to see if there would be a Bevy 0.9.1 like some in the Discord suggested .. not really a consensus yet though? https://github.com/bevyengine/bevy/milestone/9

Not that there's any good reason to do so, just thought it'd make it less likely to run into a bug when upgrading. But I'll likely tackle this next week unless someone gets to it first!

**Comment by connorcarpenter** [comment]
Supported now in https://github.com/naia-lib/naia/releases/tag/v0.14.0
