### ISSUE TITLE
Sending files and large packets

### ISSUE THREAD

**Issue by BrandonDyer64** [naia-lib/naia#105]
I need to be able to send Bevy scenes, GLTFs, WASM bins, Rhai scripts, and H.264 packets from my server to my client, all of which tend to be larger than the 508 byte limit on `naia` messages. Is there any way to do this from within `naia`?

If yes:
- How can it be done, and can I add an example to the demos?

If no:
- Is there a workaround or hack for getting `naia` to do it anyway?
- What is your recommendation for how to do it without `naia`?
- Is it a planned feature? What needs to be done to support it?

Thank you for making this fantastic set of libraries! Please let me know if there's anything I can do to help!

**Comment by connorcarpenter** [comment]
Hey Brandon, thanks for the question and your interest :slightly_smiling_face: 

Yes currently this kind of large file transfer is out of scope for `naia`. `naia`'s current purpose is to synchronize an ECS world from server->client and to send basic messages with various reliability guarantees. It should concern data that can change moment-to-moment during gameplay.

However in the past I have considered using `naia` for "all the things", even for my backend service-to-service architecture. While it is nice to imagine being able to use `naia` as a swiss-army-knife for networking, I think better solutions could exist.

Something I've been meaning to research is what crates out there exist for cross-platform HTTP requests (Wasm included). Bevy's asset loader system does a good job here on Wasm, but a better solution IMO is something like https://github.com/johanhelsing/bevy_web_asset

I can imagine a system that would be appealing to me, where a `naia` Server syncs some Entity with an "AssetComponent" to the Client, and then the Client, upon receiving an AssetComponent sends an HTTP request to the URL contained within a `Property<String>` field in that AssetComponent. Then the Server could manually control what Assets each Client currently has loaded into memory (and you'd have some kind of smart system that can dynamically detect which Assets each Client will need based on the gameplay elements currently being synced to that Client). When the Client receives an event telling it that an AssetComponent has been removed or it's Entity despawned, it could clean up the memory / local resources associated.

Similar to an internet browser, a game client using such a system could support endless future content updates.

**Comment by connorcarpenter** [comment]
Fixed / implemented with Release 0.18: https://github.com/naia-lib/naia/releases/tag/v0.18.0

**Comment by BrandonDyer64** [comment]
Love to see it! Thank you for this update!
