### ISSUE TITLE
Future feature plans

### ISSUE THREAD

**Issue by cBournhonesque** [naia-lib/naia#113]
Hey,
I'm just opening this to keep track of the future features we talked about. Feel free to close if you track them somewhere else! :)

- separate the message-passing from the ECS-replication parts of naia.
- being able to pass any struct as a message (separte change-detection `Property/Replicate` from serialiazation (which shouldn't need to derive `Property/Replicate`))
- being able to have different tick-frequencies (i.e. network send) per message/component. Being able to send messages separately from ECS-components.
- being able to split the `Protocolize` enum into multiple pieces

**Comment by connorcarpenter** [comment]
Release 0.16 implemented 3 of the above 4 points:
- separate the message-passing from the ECS-replication parts of naia
- being able to pass any struct as a message (separte change-detection Property/Replicate from serialiazation (which shouldn't need to derive Property/Replicate))
- being able to split the Protocolize enum into multiple pieces

Next plans for Naia is:
- Tick synchronization refactor
- Fragmentation of large Messages, allowing arbitrarily large Message transmission
- Transport layer abstraction (i.e. be able to run Naia over pure UDP vs the current WebRTC)
- Network-synced Resources
- Client-authoritative Replicated Components

**Comment by connorcarpenter** [comment]
Release 0.17 implemented the time synchronization refactor.

Next plans for Naia is:
- Fragmentation of large Messages, allowing arbitrarily large Message transmission
- Transport layer abstraction (i.e. be able to run Naia over pure UDP vs the current WebRTC)
- Network-synced Resources
- Client-authoritative Replicated Components

**Comment by connorcarpenter** [comment]
Release 0.18 implemented fragmentation of large Messages
Release 0.19 implemented Client-authoritative Entities

Next plans for Naia is:
- Transport layer abstraction (i.e. be able to run Naia over pure UDP vs the current WebRTC)
- Network-synced Resources

**Comment by connorcarpenter** [comment]
Release 0.20 implemented transport layer abstraction, with built-in implementations for UDP & WebRTC

Next plans for Naia is:

Network-synced Resources
