### ISSUE TITLE
Dealing with Entity Relations

### ISSUE THREAD

**Issue by cBournhonesque** [naia-lib/naia#119]
# Context

I am having issues handling relations between entities properly.
As an example; I have a 'Head' entity and a 'Segment' entity.
In the segment entity, I want to add a `HasHead(EntityProperty)` component that contains the head's entity.

If I just use naia's replication channel, i often get panics because the `HasHead` component gets sent to the server before the client has spawned the corresponding `Head` entity. The client cannot read the `net_entity_id` corresponding to the Head because it doesn't exist, and Naia panics.

# Potential solutions

- Naia has a mechanism where it waits for confirmation that the client has spawned the entity before sending the corresponding `EntityProperty`. This seems to work for messages, but not for components that get automatically replicated.
  - also, it's not ideal, because this adds a certain amount of latency before the `HasHead` component gets replicated between client and server
  
- Add some kind of ordering system, where I can replicate a group of components from client to server, and the client will handle them in the same order?
- Pre-reserve a set of entities on client/server so that we avoid panics when an net_entity doesn't match an entity in the Bevy world?
- See how other networking libraries handle this issue

**Comment by ed-curran** [comment]
I've also run into this difficulty, am curious if there's already a proper way to deal with it that i can't find. 

Similar to your proposed second solution I was thinking maybe have a way to create related entities in a batch. Such that consistency of the relations only needs to be valid once the full batch is committed.
