### ISSUE TITLE
Separate the message-passing from the ECS-replication parts of naia.

### ISSUE THREAD

**Issue by cBournhonesque** [naia-lib/naia#120]
Currently, messages need to be part of the `Protocol` enum. This means that they:
- need to implement Replicate
- their fields have to be `Property` or `EntityProperty`
- they need to derive Bevy's `Component`

All of these shouldn't be needed

**Comment by connorcarpenter** [comment]
In Release 0.16, the Component-specific derived `Replicate` trait is now separate from the derived `Message` trait
