### ISSUE TITLE
Bevy's change detection is triggered too many times

### ISSUE THREAD

**Issue by cBournhonesque** [naia-lib/naia#124]
On bevy, I rely on ChangeDetection to run a system only when a component value has changed.
For example, I want to play a sound when a player turned.

However, I noticed that ChangeDetection gets triggered multiple times when the component that gets changed is a component that gets replicated by Naia.
The 'repetition' seems to not be deterministic: sometimes the component gets updated only once, sometimes multiple times. This seems to point to some networking-related behaviour. Maybe the component gets updated multiple times because the packets are being re-sent?

However, I noticed that the component value gets updated once successfully (the character turned once), and then the update still gets re-applied. Need to investigate more..

**Comment by connorcarpenter** [comment]
I do think this is intended behavior, a client app shouldn't assume a property will only be mutated once because of redundant updates sent from the server.
