### ISSUE TITLE
Have the ability to 'turn off/turn on' replication at will for a given entity.

### ISSUE THREAD

**Issue by cBournhonesque** [naia-lib/naia#125]
A potential use-case would be animations:
- an entity dies on the server
- i want to despawn it immediately on the server, but still play animations on the entity on the client-side

For this, I would need to despawn the entity on the server without the DespawnEntity action getting replicated.

This doesn't have to for the ControlledEntity (where having a separate PredictedEntity could make it work). For example let's say there is a 'Food' entity that is being despawned; I would like to have a 'food despawning' animation that lasts 1 second on the client, but immediately despawn the food on the server.

**Comment by connorcarpenter** [comment]
I understand why this would be neat, but I'd prefer this not to be part of the API, it can be designed around.
