### ISSUE TITLE
Issue when broadcasting a message to all users when a new user connects

### ISSUE THREAD

**Issue by cBournhonesque** [naia-lib/naia#129]
I have this scenario:
- a user connects
- on the server, i get a ConnectionEvents for the user
- I tried to broadcast a SpawnSnake message to all users using `self.server.user_keys().iter().send_message()`
- the user that just connected doesn't receive the message. They only receive it if i specifically send the message to that user

This might be because it takes some time after the ConnectionEvent is received on the server before the `user_key` is added to `self.server.user_keys()` ?

I have another issue that might be related:
- I create a non-moving Segment on the server's WorldProxy (so the components don't get changed at all after it is spawned)
- when a client connects (5 seconds later), they should automatically receive this segment because of automatic replication
- the client does receive the segment entity, but with incorrect values for the replicated components (just has default values for all replicated components)

**Comment by connorcarpenter** [comment]
I could not replicate either of the above issues :/ Any chance you could give me a branch I can try that replicates it?
I have a feeling the SpawnSnake issue has something to do with how messages that have an EntityProperty are queued to only send after receiving a notification that the given Client has received said entity ... There may be an order-of-operations issue?

`Server.user_keys()` should be accurate in the `Connection` event, there's no way to trigger that event without the new `UserKey` being in there.
