### ISSUE TITLE
Update adapters to Bevy 0.10

### ISSUE THREAD

**Issue by janhohenheim** [naia-lib/naia#143]
Seeing as Bevy 0.10 is about to be released, I thought it's time to put this in the room 🙂

**Comment by connorcarpenter** [comment]
Yeah thanks! I estimate Naia will be able to be used with Bevy 0.10 within about a week after the release :+1:

**Comment by connorcarpenter** [comment]
Closed with https://github.com/naia-lib/naia/pull/144 :)
