### ISSUE TITLE
`StaticSecret` is now behind feature gate in `x25519_dalek`

### ISSUE THREAD

**Issue by Buzzec** [naia-lib/naia#153]
The new release of `x25519_dalek` puts `StaticSecret` behind a feature gate that breaks `webrtc-unreliable-client` which relies on a release candidate. This breaks most client demos.

`x25519_dalek` broke semver but it was a release candidate while `webrtc-unreliable-client` is relying on a release candidate. `webrtc-unreliable-client` also has no github repo to file an issue with.

**Comment by connorcarpenter** [comment]
Thank you @mvlabat for propogating this to the `webrtc-unreliable-client` repo :+1:
https://github.com/naia-lib/webrtc-unreliable-client/issues/6

Will fix this soon

**Comment by connorcarpenter** [comment]
I updated `webrtc-unreliable-client` to `v0.2.1`, which fixes the `x25519_dalek` dependency, so this issue should be immediately fixed on next `cargo clean`. If that doesn't work, a new version of `naia-client-socket` is on it's way.

Thank you again for the heads up @Buzzec !
