### ISSUE TITLE
Bevy demo doesn't build on Windows

### ISSUE THREAD

**Issue by djeedai** [naia-lib/naia#156]
Not sure why but it's maybe from the disabled default features?

> thread 'main' panicked at 'Unable to find a GPU! Make sure you have installed required drivers!'

I tried to just add Bevy 0.10 and there's a couple of cargo dependency resolution issues that I couldn't figure out. So didn't manage to build.

**Comment by connorcarpenter** [comment]
Aw man that's too bad! I would recommend posting in the naia Discord https://discord.gg/fD6QCtX as I think there are some Windows developers that have been through these issues. I will post this issue there now

I would love to make any changes necessary to accommodate Windows users, but I myself do not have easy access to a Windows machine, and it may take me a bit to figure out what is necessary to make it work :/ Thank you for your patience and highlighting this issue for us

**Comment by tastetest** [comment]
I've also been encountering this, but on linux, as well. Manjaro, with an nvidia GPU and my nvidia drivers are up to date.

**Comment by connorcarpenter** [comment]
Would either you @tastetest or @djeedai be able to test the Bevy demo on Windows with Release 0.21.0? (https://github.com/naia-lib/naia/pull/162). The demo now uses only default Bevy so if the main Bevy examples work for you, so should the naia Bevy demo.

**Comment by tastetest** [comment]
I was able to successfully run the new release for the bevy demo on my manjaro set up. Seems the default bevy was the right solution. I haven't tested it on windows yet though, however.

**Comment by connorcarpenter** [comment]
I will close this until someone notifies me of continued issues on Windows :+1:
