### ISSUE TITLE
BitReader reading functions are not visible outside of naia

### ISSUE THREAD

**Issue by Veritius** [naia-lib/naia#170]
The functions `read_bit` and `read_byte` in `BitReader`'s implementation are `pub(crate)` preventing outside access.
The `Serde` crate cannot be implemented outside naia due to this.

Additionally, the `BitWrite` trait has the `write_bits` function, taking a `u32`, but `BitReader` has no such parallel.

**Comment by connorcarpenter** [comment]
Thank you for your suggestion and looking into `naia` !

`write_bits` is actually only used for the BitCounter, I've renamed it for the next release to make that clearer.

`read_bit` and `read_byte` can be accessed from other crates by just calling:

`let bit = bool::de(&mut bit_reader);` and `let byte = u8::de(&mut bit_reader);` respectively.
