### ISSUE TITLE
The Serde trait is confusingly named

### ISSUE THREAD

**Issue by Veritius** [naia-lib/naia#175]
Every time I see it, I think of the crate serde, which isn't helped by the fact the trait has nothing to do with serde. Maybe a name like `Transmissible` is better?

**Comment by connorcarpenter** [comment]
Hmm, so in my mind, in the Rust ecosystem, Serde is not only used for the `serde` crate, but used in a general sense for **Ser**ialization & **de**serialization functionality - which is all the Naia Serde trait does (https://github.com/naia-lib/naia/blob/4070727125add8fee3c70e547c66243d45a33d56/shared/serde/src/serde.rs#L4).

The Naia Serde trait comes from the `naia-serde` crate (https://crates.io/crates/naia-serde), which is a heavily modified fork of https://crates.io/crates/nanoserde (which also has nothing to do with the `serde` crate)

I think that the naming makes sense in the context of the general usage of the term, but maybe theres a way we can communicate the meaning of this name better to users? Do you have any other suggestions?
