### ISSUE TITLE
Race in `Client::maintain_socket()` drops data packets

### ISSUE THREAD

**Issue by dubrowgn** [naia-lib/naia#200]
If both a `ServerConnectResponse` and data packets are pending when `Client::maintain_socket()` is called, data packets received after the `ServerConnectResponse` are dropped. This results in a significant chance of dropping the first few data packets after a new connection is established.

Also, just more in general, if a data packet is received before the `ServerConnectResponse` due to jitter, it will be dropped.

**Comment by connorcarpenter** [comment]
Dustin thank you so much for getting in the weeds here! Glad to know people are still using this. This issue is def on the todo list for next release 👍

**Comment by connorcarpenter** [comment]
Unfortunately, to fix this I would require quite an extensive refactor to my current implementation of giving the responsibility of handling entire packets to either a pre-connection or post-connection handler. As is, Naia is designed to be able to tolerate dropped packets, and so will recover soon after connection. Perhaps next release.. Thank you for looking into this though Dustin!
