### ISSUE TITLE
Native WebRTC client sockets

### ISSUE THREAD

**Issue by connorcarpenter** [naia-lib/naia#50]
It's been a long goal for naia-socket-server to support connections to both Web & Native clients at the same time..

It seems the best way to get there now is via an implementation using https://github.com/webrtc-rs, and I've created an example repo to test out connectivity between `webrtc-rs` and `naia-server-socket` here: https://github.com/naia-lib/naia-socket-webrtc-rs-example. (Thank you @billyb2 for taking a first stab at this! I used some of your code.)

Currently we're hung up on DTLS handshake ... I suspect there's a version mismatch.

webrtc-rs main issue: https://github.com/webrtc-rs/webrtc/issues/163
webrtc-rs/dtls issue: https://github.com/webrtc-rs/dtls/issues/15

**Comment by cfagot** [comment]
Links to issues you are combining are no longer valid.

**Comment by connorcarpenter** [comment]
Implemented in https://github.com/naia-lib/naia/releases/tag/v0.12.0 !
