### ISSUE TITLE
Bevy 0.8 Support

### ISSUE THREAD

**Issue by Eaven** [naia-lib/naia#78]
Hey there

Super excited to use with bevy 0.8!

Any plans to support?

**Comment by connorcarpenter** [comment]
Oh nice! Yeah Bevy 0.8 looks great and I definitely want to keep `naia` up to date :)
Not much time for me for the next 2 weeks, but will try to get to it after that.
I would be very grateful if anyone took this on, looking at 0.8's changelist it doesn't look like there's any part of `naia` that would need to change fundamentally?

**Comment by gak** [comment]
Looks like this should be closed!
